### ISSUE TITLE
Adding to Conda Forge

### ISSUE THREAD

**Issue by lilleswing** [hawk31/pyGPGO#6]
Hi!

We are adding your code to [DeepChem](https://github.com/deepchem/deepchem).
In order to get a single conda installer we have to be able to install pyGPGO via conda.
Do you have any issues with us creating a conda install on [conda-forge](https://conda-forge.org/)?

Afterwords you would be able to install pyGPGO via

```bash
conda install -c conda-forge pyGPGO
```

**Comment by hawk31** [comment]
Hello, @lilleswing 

Fine by me. Let me know when it's available.

**Comment by hawk31** [comment]
Hi! I've seen that you're using the latest version updated to PyPI (0.1.0.dev1). 
https://github.com/conda-forge/staged-recipes/pull/3458/files

This version was still a very early and I'd advise not to use it. Also, several dependencies such as `cma` are no longer required.

I have updated the project on PyPI to the latest version (0.3.0.dev1) so that there are no issues, but you may still need to correct version numbering and dependencies in your recipe.

**Comment by hawk31** [comment]
Hi! Any status update on this?
